### ISSUE TITLE
MLData STAC for Sen1Floods11

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#38]
Connects: https://github.com/azavea/noaa-flood-mapping/issues/2

Our initial assusmption in ^ was that we would be using label extension and the `source` link to link the labels with the imagery. This was result of misunderstanding the spec. The `source` link is another name for `derived_from`, it links which imagery was used to generate the labels. Of course after labels are created they generally apply to space for some time.

Therefore we need YASTAC (Yet Another STAC) to link the labels with features per experiment. Each item in this catalog is equal to a single training scene and should link in assets to all the required data. This ml-data catalog should also provide training and testing split via collections.

Target format:
```
Root Catalog
  -> Collection: "train", properties: { "label:classes" }
    -> Item: "scene", "geometry": <raster footprint>, "datetime": <raster creation time>, ...
      -> Asset: "image[_0]"
      -> Asset: "image_1"
      -> Asset: "image_<n>"
      -> Link: rel=labels, <Label STAC Item in "labels" Collection>
      -> Link: rel=labels, <Label STAC Item in "labels" Collection>
      -> Link: rel=labels, <Label STAC Item in "labels" Collection>
      -> ...
  -> Collection: "test", properties: { "label:classes" }
    -> Item: "scene", "geometry": <raster footprint>, "datetime": <raster creation time>, ...
      -> Asset: "image[_0]"
      -> Asset: "image_1"
      -> Asset: "image_<n>"
      -> Link: rel=labels, <Label STAC Item in "labels" Collection>
      -> Link: rel=labels, <Label STAC Item in "labels" Collection>
      -> Link: rel=labels, <Label STAC Item in "labels" Collection>
      -> ...
  -> Collection: "labels"
    -> Item:
      -> Asset: "labels"
```

What we're after is a script to generate these catalogs since there are many combinations and the underlying dataset may be updated.

**Comment by jpolchlo** [comment]
The suggested structure for the `scene` items is problematic.  We lose the individual extents of the label items, and since there should be no requirement for the label geometries to be clipped to the relevant region, this causes problems for the training.  We should rely on the links to the labels alone, and have an asset pointer to the raster data, with the scene item metadata describing only the raster footprint and other attributes.  Essentially, this means copying the source raster item and tagging it with links to label items.

```
Root Catalog
  -> Collection: "train", properties: { "label:classes" }
    -> Item: "scene", "geometry": <raster footprint>, "datetime": <raster creation time>, ...
      -> Asset: "image" 
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> ...
  -> Collection: "test", properties: { "label:classes" }
    -> Item: "scene", "geometry": <raster footprint>, "datetime": <raster creation time>, ...
      -> Asset: "image" 
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> ...
```

**Comment by CloudNiner** [comment]
👍 makes sense. I'll make this change over on #40.

Note that in the sen1floods11 case, the hrefs for the link label items will be absolute `https://` links to an external catalog and thus would incur http calls when they're read into RasterVision. Should I also copy the Label STAC Items into the test and train catalogs or put them into a third "labels" collection as part of this catalog? This could also be a future optimization...

**Comment by echeipesh** [comment]
@CloudNiner I have no issue with revised structure 👍

**Comment by moradology** [comment]
Because train/test expect a lot of the same information (on pain of failed jobs), we should move all the high level configuration up to the root catalog (thus making it a collection with a set of properties). Which specific information belongs at the root of such a structure is a bit of an open question (do we want to include configuration related to the RV backend?) but *at least* the label semantics belong at this higher level. If we adopt this structure the train/test split can be demoted from `collection` to `catalog` as it is unclear that there is any information specific to these random splits

```
Root Collection; properties: { "labels": [class1, class2] }
  -> Catalog: "train"
    -> Item: "scene", "geometry": <raster footprint>, "datetime": <raster creation time>, ...
      -> Asset: "image" 
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> ...
  -> Catalog: "test"
    -> Item: "scene", "geometry": <raster footprint>, "datetime": <raster creation time>, ...
      -> Asset: "image" 
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> Link: <Label STAC Item>
      -> ...
```

**Comment by CloudNiner** [comment]
@moradology makes sense, but at this point it looks like perhaps this comment belongs over on https://github.com/azavea/stac-packer/pull/80
