### ISSUE TITLE
Train RasterVision model on Sen1Floods11

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#4]
This issue is to train a flood inundation model on the output of https://github.com/azavea/noaa-flood-mapping/issues/2

This model will be the baseline benchmark for the project.
Additionally it will be the first time we source Sentinel 1 VV and VH bands as features and will help flush out any potential issues.

- [ ] Train Sen1Flood11 model from provided data.
- [ ] Use training, test, validation split in STAC format.
- [ ] Produce segmentation STAC as output (so it may be indexed with Franklin)

**Comment by moradology** [comment]
This issue requires some modifications to be completed. I'll aim to hand this off to @jamesmcclain once the following tasks are taken care of:
- [x] We need to produce Train/Test/Validation splits for the `mldata` catalog (currently, we've got Train/Test)
- [x] The splits ought to mirror those made in Sen1Floods11 to make our models as apples to apples as we can
- [x] The inference script needs to respect Train/Test/Validation splits instead of just Train/Test

PR tracking these fixes: #63
