### ISSUE TITLE
Compare USFIMR, S1, HAND models

### ISSUE THREAD

**Issue by echeipesh** [azavea/noaa-flood-mapping#58]
Train and compare USFIMR, S1 model vs USFIMR, S1, HAND model.
This should give us some idea of how much HAND has contributed to model performance.

**Comment by CloudNiner** [comment]
Depends on #57 

The new MultiRasterConfig now available in RasterVision https://github.com/azavea/raster-vision/pull/978 will need to be used in order to include the HAND, VV and VH tifs in the generated mldata catalog. Will need to write a new `rv_stac_config` in `./inference` to run RasterVision on this dataset.

**Comment by echeipesh** [comment]
This task was complete
